<?xml version="1.0" encoding="utf-8"?>
<Project>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <SolutionDirectory>$(MSBuildThisFileDirectory)</SolutionDirectory>
    </PropertyGroup>

    <!-- Version Configuration -->
    <PropertyGroup>
        <Version>6.0.0</Version>
        <MonoGameVersion>3.8.4.1</MonoGameVersion>
        <KNIVersion>4.0.9001</KNIVersion>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>MonoGame Extended and contributors</Authors>
        <PackageProjectUrl>https://github.com/MonoGame-Extended/MonoGame-Extended</PackageProjectUrl>
        <RepositoryUrl>https://github.com/MonoGame-Extended/MonoGame-Extended</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>develop</RepositoryBranch>
        <NeutralLanguage>en</NeutralLanguage>
        <PackageIcon>logo-nuget-128.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <!-- path must be relative to the individual csproj's not this .targets file -->
        <None Include="../../logos/logo-nuget-128.png" Pack="true" PackagePath="" />
        <None Include="../../README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
