<?xml version="1.0" encoding="utf-8"?>
<Project>

    <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

    <PropertyGroup>
        <ArtifactsPath>$(SolutionDirectory).artifacts/source</ArtifactsPath>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <NoWarn>NU1701</NoWarn>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!--
        MonoGame Version Selection
        - Stable build (IsPreviewBuild=false): use MonoGame 3.8.4
        - Preview Build (IsPreviewBuild=true): Use MonoGame 3.8.5-preview.#

        MonogameVersion can be overridden via command line:
        dotnet build /p:MonoGameVersion=3.8.5-preview.3
    -->
    <PropertyGroup>
        <MonogameStableVersion>3.8.4.1</MonogameStableVersion>
        <MonoGamePreviewVersion Condition="'$(MonoGamePreviewVersion)' == ''">3.8.5-preview.3</MonoGamePreviewVersion>

        <!-- Select version based on build type -->
        <MonoGameVersion Condition="'$(MonoGameVersion)' == '' AND '$(IsPreviewBuild)' == 'true'">$(MonoGamePreviewVersion)</MonoGameVersion>
        <MonoGameVersion Condition="'$(MonoGameVersion)' == '' AND '$(IsPreviewBuild)' != 'true'">$(MonoGameStableVersion)</MonoGameVersion>
    </PropertyGroup>

    <!-- MonoGame Framework References (Standard) -->
    <ItemGroup
        Condition="!$(DefineConstants.Contains('FNA')) AND !$(DefineConstants.Contains('KNI'))">
        <PackageReference Include="MonoGame.Framework.DesktopGL"
                          Version="$(MonoGameVersion)"
                          PrivateAssets="All" />
    </ItemGroup>

    <!-- FNA Framework References -->
    <ItemGroup Condition="$(DefineConstants.Contains('FNA'))">
        <ProjectReference Include="$(MSBuildThisFileDirectory)..\..\FNA\FNA.NetStandard.csproj" />
    </ItemGroup>

    <!-- KNI Framework References -->
    <ItemGroup Condition="$(DefineConstants.Contains('KNI'))">
        <PackageReference Include="nkast.Xna.Framework"
                          Version="4.0.9001" />
        <PackageReference Include="nkast.Xna.Framework.Content"
                          Version="4.0.9001" />
        <PackageReference Include="nkast.Xna.Framework.Graphics"
                          Version="4.0.9001" />
        <PackageReference Include="nkast.Xna.Framework.Audio"
                          Version="4.0.9001" />
        <PackageReference Include="nkast.Xna.Framework.Input"
                          Version="4.0.9001" />
        <PackageReference Include="nkast.Xna.Framework.Game"
                          Version="4.0.9001" />
    </ItemGroup>

</Project>
