<?xml version="1.0" encoding="utf-8"?>
<Project>

    <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />

    <PropertyGroup>
        <ArtifactsPath>$(SolutionDirectory).artifacts/source</ArtifactsPath>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <NoWarn>NU1701;CS0067;CS0168;CS0414;CS0618;CS0169;CS1591;CS1723;CS8632;CA2200;CS1574;CS1572;CS1573</NoWarn>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- MonoGame Framework References (Standard) -->
    <ItemGroup Condition="!$(DefineConstants.Contains('FNA')) AND !$(DefineConstants.Contains('KNI'))">
        <PackageReference Include="MonoGame.Framework.DesktopGL"
                          Version="$(MonoGameVersion)"
                          PrivateAssets="All" />
    </ItemGroup>

    <!-- FNA Framework References -->
    <ItemGroup Condition="$(DefineConstants.Contains('FNA'))">
        <ProjectReference Include="$(MSBuildThisFileDirectory)..\..\FNA\FNA.NetStandard.csproj" />
    </ItemGroup>

    <!-- KNI Framework References -->
    <ItemGroup Condition="$(DefineConstants.Contains('KNI'))">
        <PackageReference Include="nkast.Xna.Framework"
                          Version="$(KNIVersion)" />
        <PackageReference Include="nkast.Xna.Framework.Content"
                          Version="$(KNIVersion)" />
        <PackageReference Include="nkast.Xna.Framework.Graphics"
                          Version="$(KNIVersion)" />
        <PackageReference Include="nkast.Xna.Framework.Audio"
                          Version="$(KNIVersion)" />
        <PackageReference Include="nkast.Xna.Framework.Input"
                          Version="$(KNIVersion)" />
        <PackageReference Include="nkast.Xna.Framework.Game"
                          Version="$(KNIVersion)" />
    </ItemGroup>

</Project>
