################################################################################
### Build MonoGame.Extended (Release)
### Performs a build, test, then pack of the MonoGame.Extended source code
### from a specified branch. Once the build job is finished, the deploy job
### will upload the nupkg files to NuGet.
###
###     - Can be triggered manually with workflow_dispatch
###     - Allows specifying a branch (defaults to develop)
###     - Version numbers are determined by the project properties on the branch
################################################################################
name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from (e.g., develop, version/6.0.0)'
        required: true
        type: string
        default: 'develop'

jobs:
  build:
    name: "Build MonoGame.Extended"
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Build MonoGame.Extended
        run: dotnet build MonoGame.Extended.sln --nologo --verbosity minimal --configuration Release

      - name: Test MonoGame.Extended
        run: xvfb-run -a -s "-screen 0 1024x768x24" dotnet test MonoGame.Extended.sln --nologo --verbosity minimal --configuration Release

      - name: Pack MonoGame.Extended
        run: dotnet pack MonoGame.Extended.sln --nologo --verbosity minimal --configuration Release

      - name: Pack Kni.Extended
        run: dotnet pack KNI.Extended.sln --nologo --verbosity minimal --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./.artifacts/source/package/release/*.nupkg

  deploy:
    name: "Deploy NuGets"
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./.artifacts

      - name: Push Packages to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_ACCESS_TOKEN }}
        run: |
          for PACKAGE in .artifacts/*.nupkg; do
            dotnet nuget push "$PACKAGE" --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key "$NUGET_API_KEY"
          done
